### ISSUE TITLE
Add "How to Use" Section to README.md

### ISSUE THREAD

**Issue by abstractionjackson** [freeCodeCampSF/FCCSF#44]
Best practices for a README include instructions for setting up the project on a local.

**Comment by tymeart** [comment]
I'm going to work on adding a Getting Started section in the README.

**Comment by tymeart** [comment]
Well it's been added now. There's still a lot that could be added on contributing and git workflow (how to deal with conflicts, making pull requests, etc), but I guess this specific issue is resolved.
