### ISSUE TITLE
Header padding

### ISSUE THREAD

**Issue by DevinCLane** [freeCodeCampSF/FCCSF#62]
The "about" in our header bar sits right on the edge of the viewport. Let's give it some more padding on its right side.

**Comment by xChristianZx** [comment]
Just made a quick fix for this. For future reference, may want to look into using the actual bootstrap navbar component to handle this layout.

**Comment by DevinCLane** [comment]
oh awesome! Thanks for looking into it, I'd love to see a demo of the fix in one of our upcoming meetings
