### ISSUE TITLE
Github link incorrect

### ISSUE THREAD

**Issue by tymeart** [freeCodeCampSF/FCCSF#8]
The link when you hover over the Github icon takes you to the Meetup page instead of to this Github repo.

This is a good first issue for beginners! :]

**Comment by JulieBoberg** [comment]
It's the link in the footer as far as I could see. A great first issue.

**Comment by prathamesh-borse** [comment]
Can i still work on this issue?

**Comment by JulieBoberg** [comment]
Absolutely! Let me know if you have any questions.

**Comment by prathamesh-borse** [comment]
I think the link is Working Properly now..

**Comment by JulieBoberg** [comment]
I don't see a pull request to merge your code with our main branch. You might want to check that you aimed you pushed to the right repository. If you need help you can reach out to us on our slack channel and we'd be happy to walk you through!

**Comment by tymeart** [comment]
It does look like the link was fixed at some point. It's correct now.

**Comment by tymeart** [comment]
Ah, it was Ola who fixed it [here](https://github.com/freeCodeCampSF/FCCSF/commit/2d88a494f9ff14207910cccfe720c128f8395a9d#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051). I guess we should close issue #41 too then.
